/u/bolade/ECE571_SV/PROJ/Design/modules/package.sv
/u/bolade/ECE571_SV/PROJ/Design/modules/ALU.sv
/u/bolade/ECE571_SV/PROJ/Design/modules/MIPS.sv
/u/bolade/ECE571_SV/PROJ/Design/modules/adder.sv
/u/bolade/ECE571_SV/PROJ/Design/modules/conditionchecker.sv
/u/bolade/ECE571_SV/PROJ/Design/modules/controller.sv
/u/bolade/ECE571_SV/PROJ/Design/modules/datamemory.sv
/u/bolade/ECE571_SV/PROJ/Design/modules/exemempipelinereg.sv
/u/bolade/ECE571_SV/PROJ/Design/modules/exestage.sv
/u/bolade/ECE571_SV/PROJ/Design/modules/forwarding.sv
/u/bolade/ECE571_SV/PROJ/Design/modules/hazarddetection.sv
/u/bolade/ECE571_SV/PROJ/Design/modules/idexepipelinereg.sv
/u/bolade/ECE571_SV/PROJ/Design/modules/idstage.sv
/u/bolade/ECE571_SV/PROJ/Design/modules/ifidpipelinereg.sv
/u/bolade/ECE571_SV/PROJ/Design/modules/ifstage.sv
/u/bolade/ECE571_SV/PROJ/Design/modules/instructionmemory.sv
/u/bolade/ECE571_SV/PROJ/Design/modules/memstage.sv
/u/bolade/ECE571_SV/PROJ/Design/modules/memwbpipelinereg.sv
/u/bolade/ECE571_SV/PROJ/Design/modules/mux.sv
/u/bolade/ECE571_SV/PROJ/Design/modules/reg.sv
/u/bolade/ECE571_SV/PROJ/Design/modules/regfile.sv
/u/bolade/ECE571_SV/PROJ/Design/modules/signextend.sv
/u/bolade/ECE571_SV/PROJ/Design/modules/wbstage.sv
/u/bolade/ECE571_SV/PROJ/Design/modules/testbench.sv
